core/urls.py
from django.urls import path,include
from django.conf.urls import url
from .views import Home,PuntoventaViews,CajeroViews,TermnalesViews,CajeroCreate,Reportes,PuntoVentaCreate,TerminalCreate,CajeroUpdate,CajeroDelete,cajero_inactivar,PuntoVentaUpdate,puntoventa_inactivar,TerminalUpdate,terminal_inactivar, ajax_reportes
from django.contrib.auth import views as auth_views





urlpatterns = [
    #path('admin/', admin.site.urls),
    path('',Home.as_view(),name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='login/login-page.html'),
    	name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='login/login-page.html'),
    	name='logout'),
    #Terminales
    path('terminalesall', TermnalesViews.as_view(), name='terminalesall'),
    url(r'^terminal_crear$', TerminalCreate.as_view(),name='terminal_crear'),
    path('terminal_editar/<pk>', TerminalUpdate.as_view(),name='terminal_editar'),
    path('terminal_eliminar/<id_pos_pc>', terminal_inactivar, name='terminal_eliminar'),

    #Puntos de Venta
    path('allpv', PuntoventaViews.as_view(), name='allpv'),
    url(r'^puntoventa_crear$', PuntoVentaCreate.as_view(),name='puntoventa_crear'),
    path('puntoventa_editar/<pk>', PuntoVentaUpdate.as_view(),name='puntoventa_editar'),
    path('puntoventa_eliminar/<id_pv>', puntoventa_inactivar, name='puntoventa_eliminar'),
    
    #Cajeros
    url(r'^cajeros_crear$', CajeroCreate.as_view(),name='cajeros_crear'),
    path('cajerosall', CajeroViews.as_view(), name='cajerosall'),
    path('cajeros_editar/<pk>', CajeroUpdate.as_view(), name='cajeros_editar'),
    path('cajeros_eliminar/<id_cajero>', cajero_inactivar, name='cajeros_eliminar'),
    
    #Reportes
    path('reportes', Reportes.as_view(), name='Reportes'),
    path('ajax_reportes', ajax_reportes, name='ajax_reportes')

]

doble_machuka/urls.py
from django.contrib import admin
from django.urls import path,include




urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include(('core.urls','core'), namespace='core'))
]

core/forms.py
from django import forms
from .models import PuntoVenta, Cajero,PosPc

class CajeroForm(forms.ModelForm):

	class Meta:
		model = Cajero

		CHOICES = [('1', 'ACTIVO'), ('2', 'INACTIVO')]


		fields = [

		'nombre_cajero',
		'clave_cajero',
		'estado_cajero',
		'id_pos_pc',


		]

		labels = {

		'nombre_cajero': 'Nombre Cajero',
		'clave_cajero': 'Clave Cajero',
		'estado_cajero': 'Estado Cajero',
		'id_pos_pc': 'Terminal Asignada'


		}

		widgets = {

		'nombre_cajero': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Nombre Cajero'}),
		'clave_cajero': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Clave Cajero'}),
		'estado_cajero': forms.Select(attrs={'class':'form-control'}),
		'id_pos_pc': forms.Select(attrs={'class':'form-control'}),

		

		}
	

		

"""class UsuariosForm(forms.ModelForm):

	class Meta:
		model = Usuarios


		fields = [

		'nombre_usuarios',
		'estado_usuarios',
		'ip_usuarios',


		]

		labels = {

		'nombre_usuarios': 'Nombre Usuario',
		'estado_usuarios': 'Estado Usuario',
		'ip_usuarios': 'IP Usuario',


		}

		widgets = {

		'nombre_usuarios': forms.TextInput(attrs={'class':'form-control'}),
		'estado_usuarios': forms.TextInput(attrs={'class':'form-control'}),
		'ip_usuarios': forms.TextInput(attrs={'class':'form-control'}),


		}"""


class PuntoVentaForm(forms.ModelForm):

	class Meta:
		model = PuntoVenta

		CHOICES = [('1', 'ACTIVO'), ('2', 'INACTIVO')]

		fields = [

		'nombre_pv', 
    	'estado_pv',
    	'user',
    	'localidad',
    

		]

		labels = {

		'nombre_pv': 'Punto de Venta', 
    	'estado_pv': 'Estado Punto de Venta',
    	'user': 'Usuario',
    	'localidad': 'Localidad',


		}

		widgets = {

		'nombre_pv': forms.TextInput(attrs={'class':'form-control','placeholder':'Nombre Punto de Venta'}), 
    	'estado_pv': forms.Select(attrs={'class':'form-control','placeholder':'Estado Punto de Venta'}),
    	'user': forms.Select(attrs={'class':'form-control',}),
    	'localidad': forms.TextInput(attrs={'class':'form-control','placeholder':'Localidad'}),

		}


class TerminalForm(forms.ModelForm):

	class Meta:
		model = PosPc

		CHOICES = [('1', 'ACTIVO'), ('2', 'INACTIVO')]


		fields = [

		'codigo_pos_pc',
    	'estado_pos_pc',
    	'id_pv',
    

		]

		labels = {

		'codigo_pos_pc': 'Codigo Terminal', 
    	'estado_pos_pc': 'Estado Terminal',
    	'id_pv': 'Punto de Venta Asignado',


		}

		widgets = {

		'codigo_pos_pc': forms.TextInput(attrs={'class':'form-control','placeholder':'Codigo Terminal'}), 
    	'estado_pos_pc': forms.Select(attrs={'class':'form-control','placeholder':'Estado Terminal'}),
    	'id_pv': forms.Select(attrs={'class':'form-control','placeholder':'Punto de Venta'}),

		}

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,TemplateView
from .models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from .forms import CajeroForm,PuntoVentaForm,TerminalForm
from django.http import HttpResponse, JsonResponse
import json
from django.db.models import Count


from django.template.response import TemplateResponse
from django.db.models import Sum
import datetime


# Create your views here.
class Home(LoginRequiredMixin,TemplateView):
	
	template_name=	'dashboard.html'
	login_url='/login'
	context_object_name='obj'

def set_table_data(allset_aggregate, allset_carton_charts_aggregate):
	table_data = []
	for i in range(len(allset_aggregate)):
		line_keno = allset_aggregate[i]
		line_cartas = allset_carton_charts_aggregate[i]
		
		# add tickets from two tables (keno + cartas)
		line_cartas['tickets'] += line_keno['tickets']

		# add ventas from two tables (keno + cartas)
		line_cartas['ventas'] += line_keno['ventas']

		# calculate premios
		filterd_set_ganadoreskeno = GanadoresKeno.objects.all().filter( id_c_k__id_cajero__id_pos_pc__id_pv__localidad=line_keno['id_cajero__id_pos_pc__id_pv__localidad'] ).filter( id_c_k__id_cajero__id_pos_pc__id_pv__nombre_pv=line_keno['id_cajero__id_pos_pc__id_pv__nombre_pv'] )
		premios_ganadoreskeno = filterd_set_ganadoreskeno.aggregate(Sum('valor_ganado_k'))['valor_ganado_k__sum']
		
		filterd_set_ganadorescartas = GanadoresCartas.objects.all().filter( id_c_c__id_cajero__id_pos_pc__id_pv__localidad=line_keno['id_cajero__id_pos_pc__id_pv__localidad'] ).filter( id_c_c__id_cajero__id_pos_pc__id_pv__nombre_pv=line_keno['id_cajero__id_pos_pc__id_pv__nombre_pv'] )
		premios_ganadorescartas = filterd_set_ganadorescartas.aggregate(Sum('valor_ganado_c'))['valor_ganado_c__sum']

		line_cartas['premios'] = premios_ganadoreskeno + premios_ganadorescartas
		
		# calculate saldo
		line_cartas['saldo'] = line_cartas['premios'] - line_cartas['ventas']

		# calculate percentage
		if line_cartas['ventas'] != 0:
			line_cartas['percentage'] = round(line_cartas['premios'] * 100 / line_cartas['ventas'], 2)
		else:
			line_cartas['percentage'] = 0

		table_data.append(line_cartas)
	return table_data


# class Reportes(LoginRequiredMixin,ListView):
class Reportes(ListView):
    
	model:CartonKeno
	template_name=	'reportes.html'
	context_object_name='obj'
	queryset = []
	allset = CartonKeno.objects.all()
	allset_aggregate = allset.values('id_cajero__id_pos_pc__id_pv__localidad', 'id_cajero__id_pos_pc__id_pv__nombre_pv').order_by('id_cajero__id_pos_pc__id_pv__localidad').annotate(tickets=Count('id_c_k'), ventas=Sum('valor_apuesta_k'))
	# queryset.append(allset_aggregate)

	allset_carton_charts = CartonCartas.objects.all()
	allset_carton_charts_aggregate = allset_carton_charts.values('id_cajero__id_pos_pc__id_pv__localidad', 'id_cajero__id_pos_pc__id_pv__nombre_pv').order_by('id_cajero__id_pos_pc__id_pv__localidad').annotate(tickets=Count('id_c_c'), ventas=Sum('valor_apuesta_c'))
	    
	
	# add ventas from two queryset list
	table_data = set_table_data(allset_aggregate, allset_carton_charts_aggregate)

	queryset.append(table_data)

	model:PuntoVenta
	filterset_localidad = PuntoVenta.objects.values('localidad').annotate(dcount=Count('localidad'))
	queryset.append(filterset_localidad)

	filterset_pdv = PuntoVenta.objects.values('nombre_pv').annotate(dcount=Count('nombre_pv'))
	queryset.append(filterset_pdv)



def ajax_reportes(request):
    # get post data
    localidad = request.POST.get('localidad') # localidad
    nombre_pv = request.POST.get('nombre_pv') # nombre_pv
    selecclonar = request.POST.get('selecclonar') # selecclonar (hoy, selecclone de)
    inicial = request.POST.get('inicial') # inicial date
    final = request.POST.get('final') # final date
    
	# response queryset as a list
    queryset = []

	# count and sum
    pdvs = 0
    tickets = 0
    ventas = 0 # sum of ventas from two tables (carton_keno & carton_cartas)
    ventas_list = [] # each ventas from two tables (carton_keno & carton_cartas)
    premios = 0 # sum of premios from two tables (carton_keno & carton_cartas)
    premios_list = [] # each premios from two tables (carton_keno & carton_cartas)
    saldo = 0
    percentage = 0

    if localidad == "" and nombre_pv == "":
    	# get all QuerySet
        # allset from CartonKeno
	    # allset = CartonKeno.objects.values('id_cajero').order_by('id_cajero').annotate(count=Count('id_cajero'))
	    allset = CartonKeno.objects.all().filter(fecha_keno__gte=inicial, fecha_keno__lte=final)
	    allset_aggregate = allset.values('id_cajero__id_pos_pc__id_pv__localidad', 'id_cajero__id_pos_pc__id_pv__nombre_pv').order_by('id_cajero__id_pos_pc__id_pv__localidad').annotate(tickets=Count('id_c_k'), ventas=Sum('valor_apuesta_k'))
		
		# allset from CartonCartas
	    allset_carton_charts = CartonCartas.objects.all().filter(fecha_cartas__gte=inicial, fecha_cartas__lte=final)
	    allset_carton_charts_aggregate = allset_carton_charts.values('id_cajero__id_pos_pc__id_pv__localidad', 'id_cajero__id_pos_pc__id_pv__nombre_pv').order_by('id_cajero__id_pos_pc__id_pv__localidad').annotate(tickets=Count('id_c_c'), ventas=Sum('valor_apuesta_c'))
	    
		# add ventas from two queryset list
	    table_data = set_table_data(allset_aggregate, allset_carton_charts_aggregate)
		
		# append all set for datatable
	    queryset.append(table_data)

		# get pdvs
    else:   	 
        # filtered QuerySet
	    # filterd_set from CartonKeno
	    if localidad != "" and nombre_pv != "":
	    	filterd_set = CartonKeno.objects.all().filter(fecha_keno__gte=inicial, fecha_keno__lte=final).filter( id_cajero__id_pos_pc__id_pv__localidad=localidad ).filter( id_cajero__id_pos_pc__id_pv__nombre_pv=nombre_pv )
	    	filterd_set_aggregate = filterd_set.values('id_cajero__id_pos_pc__id_pv__localidad', 'id_cajero__id_pos_pc__id_pv__nombre_pv').order_by('id_cajero__id_pos_pc__id_pv__localidad').annotate(tickets=Count('id_c_k'), ventas=Sum('valor_apuesta_k'))
	    elif localidad == "":
		    filterd_set = CartonKeno.objects.all().filter(fecha_keno__gte=inicial, fecha_keno__lte=final).filter( id_cajero__id_pos_pc__id_pv__nombre_pv=nombre_pv )
		    filterd_set_aggregate = filterd_set.values('id_cajero__id_pos_pc__id_pv__localidad', 'id_cajero__id_pos_pc__id_pv__nombre_pv').order_by('id_cajero__id_pos_pc__id_pv__localidad').annotate(tickets=Count('id_c_k'), ventas=Sum('valor_apuesta_k'))
	    else: # nombre_pv == "":
    		filterd_set = CartonKeno.objects.all().filter(fecha_keno__gte=inicial, fecha_keno__lte=final).filter( id_cajero__id_pos_pc__id_pv__localidad=localidad )
	    	filterd_set_aggregate = filterd_set.values('id_cajero__id_pos_pc__id_pv__localidad', 'id_cajero__id_pos_pc__id_pv__nombre_pv').order_by('id_cajero__id_pos_pc__id_pv__localidad').annotate(tickets=Count('id_c_k'), ventas=Sum('valor_apuesta_k'))
		
		# filter_set from CartonCartas
	    if localidad != "" and nombre_pv != "":
		    filterd_set_cartas = CartonCartas.objects.all().filter(fecha_cartas__gte=inicial, fecha_cartas__lte=final).filter( id_cajero__id_pos_pc__id_pv__localidad=localidad ).filter( id_cajero__id_pos_pc__id_pv__nombre_pv=nombre_pv )#.filter(fecha_keno__range=["2011-01-01", "2021-01-31"])
		    filterd_set_aggregate_cartas = filterd_set_cartas.values('id_cajero__id_pos_pc__id_pv__localidad', 'id_cajero__id_pos_pc__id_pv__nombre_pv').order_by('id_cajero__id_pos_pc__id_pv__localidad').annotate(tickets=Count('id_c_c'), ventas=Sum('valor_apuesta_c'))
	    elif localidad == "":
		    filterd_set_cartas = CartonCartas.objects.all().filter(fecha_cartas__gte=inicial, fecha_cartas__lte=final).filter( id_cajero__id_pos_pc__id_pv__nombre_pv=nombre_pv )
		    filterd_set_aggregate_cartas = filterd_set_cartas.values('id_cajero__id_pos_pc__id_pv__localidad', 'id_cajero__id_pos_pc__id_pv__nombre_pv').order_by('id_cajero__id_pos_pc__id_pv__localidad').annotate(tickets=Count('id_c_c'), ventas=Sum('valor_apuesta_c'))
	    else: # nombre_pv == "":
    		filterd_set_cartas = CartonCartas.objects.all().filter(fecha_cartas__gte=inicial, fecha_cartas__lte=final).filter( id_cajero__id_pos_pc__id_pv__localidad=localidad )
	    	filterd_set_aggregate_cartas = filterd_set_cartas.values('id_cajero__id_pos_pc__id_pv__localidad', 'id_cajero__id_pos_pc__id_pv__nombre_pv').order_by('id_cajero__id_pos_pc__id_pv__localidad').annotate(tickets=Count('id_c_c'), ventas=Sum('valor_apuesta_c'))
		
		# add ventas from two queryset list (CartonKeno + CartonCartas)
	    table_data = set_table_data(filterd_set_aggregate, filterd_set_aggregate_cartas)
		# append filtered set for datatable
	    queryset.append(table_data)

		# get pdvs
	    pdvs = len(table_data)

		# calculate tickets
		# Count( CartonKeno.id_ck )
	    tickets = filterd_set.count() + filterd_set_cartas.count()

		# calculate the ventas
		# SUM( CartonKeno.valor_apuesta_k + CartonCartas.valor_apuesta_c )
	    vantas_cartonkeno = filterd_set.aggregate(Sum('valor_apuesta_k'))['valor_apuesta_k__sum']
	    
		# filterd_set_cartonCarts = CartonCartas.objects.all().filter( id_cajero__id_pos_pc__id_pv__localidad=localidad ).filter( id_cajero__id_pos_pc__id_pv__nombre_pv=nombre_pv ).filter( fecha_cartas__gte=inicial ).filter( fecha_cartas__lte=final )
	    if localidad != "" and nombre_pv != "":
		    filterd_set_cartonCarts = CartonCartas.objects.all().filter(fecha_cartas__gte=inicial, fecha_cartas__lte=final).filter( id_cajero__id_pos_pc__id_pv__localidad=localidad ).filter( id_cajero__id_pos_pc__id_pv__nombre_pv=nombre_pv )
	    elif localidad == "":
    		filterd_set_cartonCarts = CartonCartas.objects.all().filter(fecha_cartas__gte=inicial, fecha_cartas__lte=final).filter( id_cajero__id_pos_pc__id_pv__nombre_pv=nombre_pv )
	    else: # nombre_pv == "":

core/templates/cajeros_delete.html
<div class="modal-dialog modal-lg">
	<div class="modal-content">
		<form method="POST" role="form" action="{% url 'core:cajeros_eliminar' obj.pk %}">
			{% csrf_token %}
			<div class="modal-header az-content-label bd-0 tx-white bg-indigo">
				Inactivar Cajero</div>
			<div class="modal-body">
				<h3>Desea inactivar el registro de {{obj.nombre_cajero}}?</h3>
			</div>
			<div class="modal-footer">
				<div class="row">
					<div class="col">
						<button type="button" class="btn btn-danger"id="btninactivar" >Inactivar</button>
						<button class="btn btn-default" type="button" onclick="return cerrar_modal()">Cancelar</button>
					</div>
				</div>
			</div>
		</form>	
	</div>
</div>	

<script>
$(document).ready(function(){
	var token = $('input[name=csrfmiddlewaretoken]').val();
	$.ajaxSetup({
		beforeSend: function(xhr, settings){
			if (!(/^http:.*/.test(settings.url) || /^http:.*/.test(settings.url))){
				xhr.setRequestHeader("X-CSRFToken", token);
			}
		}
	});
	$("#btninactivar").click(function(e){
		e.preventDefault();

		var id = {{ obj.id_cajero}};
		var template="{% url 'core:cajeros_eliminar' obj.id_cajero %}";
		var data={"id_cajero":id};
		data = JSON.stringify(data);

		$.ajax({
			type: "POST",
			url: template,
			data: data,
			beforeSend: function(xhr,settings){
				$.ajaxSettings.beforeSend(xhr,settings);
			},
			success: function(response){
				console.log(response);
				cerrar_modal();
				alert(response);

			},
			error: function(jqXHR, textStatus, errorThrow){
				console.log(textStatus,errorThrow);
				cerrar_modal();
			}
		});

	});
});
</script>

core/templates/cajerosall.html
{%extends 'base.html'%}

{%block content%}
<div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold az-content-label tx-indigo">Listado de Cajeros</h6>
                  <div class="col-md-6">
                  <a id="btnCreate" onclick="return abrir_modal('{% url 'core:cajeros_crear' %}')"><i class="fa fa-plus-circle fa-3x" style="float:right; margin-right:20px;"></i></a>
                </div>
                </div>
                    
                  
                <!-- Card Body -->
                <div class="card-body">
                  {%if not obj%}
                   <div class="alert alert-info">No Hay Cajeros Registrados</div>
                  {% else %}
                  <table class="table table-striped table-hover">
                    <thead>
                      <th>ID</th>
                      <th>NOMBRE CAJERO</th>
                      <th>CODIGO</th>
                      <th>ESTADO</th>
                      <th>TERMINAL ASIGNADA</th>
                      <th class="all">ACCIONES</th>
                    </thead>
                    <tbody>
                      <tr>
                      {%for item in obj %}
                      <td>{{ item.id_cajero }}</td>
                      <td>{{item.nombre_cajero}}</td>
                      <td>{{ item.clave_cajero}}</td>
                      <td>{{item.estado_cajero}}</td>
                      <td>{{item.id_pos_pc.codigo_pos_pc}}</td>
                      <td>
                        <a class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'core:cajeros_editar' item.id_cajero %}')">
                          <i class="far fa-edit"></i></a>
                        <a class="btn  btn-danger btn-circle remove" onclick="return abrir_modal('{% url 'core:cajeros_eliminar' item.id_cajero %}')"><i class="far fa-trash-alt"></i></a>
                      </td>
                      </tr>
                      {%endfor%}
                    </tbody>
                  </table>
                  {%endif%}
                </div>
              </div>
{%endblock%}

core/templates/home.html
{%extends 'base.html'%}

core/templates/puntoventa.html
<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header az-content-label bd-0 tx-white bg-indigo">
				Agregar Punto de Venta</div>
				<div class="modal-body bg-gray-200 bd-0">
					<form method="POST" role="form" action="{% url 'core:puntoventa_crear' %}" class="create-form">
					{% csrf_token %}
					<div class="row">
						<div class="col-4">
							<div class="input-group">
								{{ form.nombre_pv}}

							</div>
						</div>
					<div class="row">
						<div class="col-3">
							<div class="input-group">
								{{ form.estado_pv}}

							</div>
						</div>
						<div class="col-3">
							<div class="input-group">
								{{ form.user}}

							</div>
						</div>
						<div class="col-4">
							<div class="input-group">
								{{ form.localidad}}

							</div>
						</div>
					</div>
				</div>
			<div class="modal-footer">
				<button class="btn btn-az-primary" type="submit">Agregar</button>
				<a class="btn btn-outline-light" href="{% url 'core:allpv' %}">Cancelar</a>
			</div>
			</form>
		</div>
	</div>
</div>

core/templates/puntoventa_edit.html
<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header az-content-label bd-0 tx-white bg-indigo">
				Editar Punto de Venta</div>
				<div class="modal-body bg-gray-200 bd-0">
					<form method="POST" role="form" action="{% url 'core:puntoventa_editar' obj.pk %}" class="create-form">
					{% csrf_token %}
					<div class="row">
						<div class="col-4">
							<div class="input-group">
								{{ form.nombre_pv}}

							</div>
						</div>
					<div class="row">
						<div class="col-3">
							<div class="input-group">
								{{ form.estado_pv}}

							</div>
						</div>
						<div class="col-3">
							<div class="input-group">
								{{ form.user}}

							</div>
						</div>
						<div class="col-4">
							<div class="input-group">
								{{ form.localidad}}

							</div>
						</div>
					</div>
				</div>
			<div class="modal-footer">
				<button class="btn btn-az-primary" type="submit">Editar</button>
				<a class="btn btn-outline-light" href="{% url 'core:allpv' %}">Cancelar</a>
			</div>
			</form>
		</div>
	</div>
</div>

core/templates/terminal_edit.html
<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header az-content-label bd-0 tx-white bg-indigo">
				Editar Terminal</div>
				<div class="modal-body bg-gray-200 bd-0">
					<form method="POST" role="form" action="{% url 'core:terminal_editar' obj.pk %}" class="create-form">
					{% csrf_token %}
					<div class="row">
						<div class="col-3">
							<div class="input-group">
								{{ form.codigo_pos_pc}}

							</div>
						</div>
					<div class="row">
						<div class="col-5">
							<div class="input-group">
								{{ form.estado_pos_pc}}

							</div>
						</div>
						<div class="col-7">
							<div class="input-group">
								{{ form.id_pv}}

							</div>
						</div>
					</div>
				</div>
			<div class="modal-footer">
				<button class="btn btn-az-primary" type="submit">Editar</button>
				<a class="btn btn-outline-light" href="{% url 'core:terminalesall' %}">Cancelar</a>
			</div>
			</form>
		</div>
	</div>
</div>

core/templates/terminalesall.html
{%extends 'base.html'%}

{%block content%}
<div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold az-content-label tx-indigo">Listado de Terminales</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Acciones</div>
                      <a class="dropdown-item" onclick="return abrir_modal('{% url 'core:terminal_crear' %}')"><i class="far fa-calendar-plus"></i>Nuevo Terminal</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  {%if not obj%}
                   <div class="alert alert-info">No Hay Terminales Registrados</div>
                  {%endif%}
                  <table class="table table-striped table-hover">
                    <thead>
                      <th>ID</th>
                      <th>CODIGO TERMINAL</th>
                      <th>ESTADO TERMINAL</th>
                      <th>PUNTO DE VENTA ASIGNADO</th>
                      <th class="all">ACCIONES</th>
                    </thead>
                    <tbody>
                      <tr>
                      {%for item in obj %}
                      <td>{{ item.id_pos_pc }}</td>
                      <td>{{item.codigo_pos_pc}}</td>
                      <td>{{ item.estado_pos_pc}}</td>
                      <td>{{item.id_pv.nombre_pv}}</td>
                      <td>
                        <a class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'core:terminal_editar' item.id_pos_pc %}')">
                          <i class="far fa-edit"></i></a>
                        <a class="btn  btn-danger btn-circle " onclick="return abrir_modal('{% url 'core:terminal_eliminar' item.id_pos_pc %}')"><i class="far fa-trash-alt"></i></a>
                      </td>
                      </tr>
                      {%endfor%}
                    </tbody>
                  </table>
                </div>
              </div>
{%endblock%}

{%block page_js%}

<script>
  
  $(document).ready(function(){
    $('.table').DataTable();
    });
</script>
{%endblock%}